### ISSUE TITLE
 The remote name could not be resolved: 'htmltopdforimage.com'

### ISSUE THREAD

**Issue by jonatahBenatti** [mrdaghestani/HtmlToPdfOrImage#7]
Having the error message back when calling for the 'var result = api.Convert("string");'

System.Net.WebException was unhandled by user code
  HResult=-2146233079
  Message=The remote name could not be resolved: 'htmltopdforimage.com'
  Source=System
  StackTrace:
       at System.Net.HttpWebRequest.GetRequestStream(TransportContext& context)
       at System.Net.HttpWebRequest.GetRequestStream()
       at HtmlToPdfOrImage.Api.Execute(String url, String data)
       at HtmlToPdfOrImage.Api.Execute[T](String url, String data)
       at HtmlToPdfOrImage.Api.Execute[T](String url, Object data)
       at HtmlToPdfOrImage.Api.Convert(GenerateSettings settings)
       at HtmlToPdfOrImage.Api.Convert(String html, GenerateSettings settings)

Is the API website down?

**Comment by mrdaghestani** [comment]
Hello dear,
That was a DNS problem, It's ok now, try it.
If you wanna use it in your own server please use [HtmlPI](https://github.com/mrdaghestani/HtmlPI).
